6

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -50,114 +50,118 @@
 
 #    #***************
 #    # dboedited
-#    #*************
-# name: 'Terraform'
-# # dboedited
-# on:
-#   workflow_dispatch:
-#     inputs:
-#       terraform_action:
-#         type: choice
-#         description: select terraform action
-#         options:
-#         - apply
-#         - destroy
-#         required: true
-#   push:
+   #*************
+name: 'Terraform'
+# dboedited
+on:
+  workflow_dispatch:
+    inputs:
+      terraform_action:
+        type: choice
+        description: select terraform action
+        options:
+        - apply
+        - destroy
+        required: true
+  push:
 
-#     branches: [ "main" ]
-# # dboedited
-# jobs:
-#   terraform:
-#     name: 'Terraform'
-#     env:
-#         # AWS Secrets
-#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEVOPS_ACCESS_KEY_ID }}
-#         AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_DEVOPS_SECRET_ACCESS_KEY }}
+    branches: [ "main" ]
+# dboedited
+jobs:
+  terraform:
+    name: 'Terraform'
+    env:
+        # AWS Secrets
+        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEVOPS_ACCESS_KEY_ID }}
+        # AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_DEVOPS_SECRET_ACCESS_KEY }}
+            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_DEFAULT_REGION}}
 
-#     runs-on: ubuntu-latest
-#     environment: production
 
-#     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
-#   # dboedited
-#     defaults:
-#       run:
-#         shell: bash
-#   # dboedited
-#     steps:
-#     # Checkout the repository to the GitHub Actions runner
-#     - name: Checkout
-#       uses: actions/checkout@v3
+    runs-on: ubuntu-latest
+    environment: production
 
-# # ===================DBO TERROFORM CLOUD=================
-#     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
-#     # - name: Setup Terraform
-#     #   uses: hashicorp/setup-terraform@v1
-#     #   with:
-#     #     cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
+  # dboedited
+    defaults:
+      run:
+        shell: bash
+  # dboedited
+    steps:
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v3
 
-#         # - name: Setup Terraform
-#     #   uses: hashicorp/setup-terraform@v1
-#     #   with:
-#     #     cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+# ===================DBO TERROFORM CLOUD=================
+    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+    # - name: Setup Terraform
+    #   uses: hashicorp/setup-terraform@v1
+    #   with:
+    #     cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-#     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+        # - name: Setup Terraform
+    #   uses: hashicorp/setup-terraform@v1
+    #   with:
+    #     cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-#    #***************
-#    # dboedited
-#    #*************
-#     - name: Terraform Init
-#       uses: hashicorp/terraform-github-actions@master
-#       with:
-#         tf_actions_version: 0.14.3
-#         tf_actions_subcommand: 'init'
-#         tf_actions_working_dir: '.'
-#         tf_actions_comment: true
-#         args: '-var="instance_type=t2.medium"'
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
 
-#     # Checks that all Terraform configuration files adhere to a canonical format
-#     # - name: Terraform Format
-#     #   run: terraform fmt -check
+   #***************
+   # dboedited
+   #*************
+    - name: Terraform Init
+      uses: hashicorp/terraform-github-actions@master
+      with:
+        tf_actions_version: 0.14.3
+        tf_actions_subcommand: 'init'
+        tf_actions_working_dir: '.'
+        tf_actions_comment: true
+        args: '-var="instance_type=t2.medium"'
 
-#     # Generates an execution plan for Terraform
-#    #***************
-#    # dboedited
-#    #*************
-#     - name: Terraform Plan
-#       uses: hashicorp/terraform-github-actions@master
-#       with:
-#         tf_actions_version: 0.14.3
-#         tf_actions_subcommand: 'plan'
-#         tf_actions_working_dir: '.'
-#         tf_actions_comment: true
-#         args: '-var="instance_type=t2.medium"'
+    # Checks that all Terraform configuration files adhere to a canonical format
+    # - name: Terraform Format
+    #   run: terraform fmt -check
 
-#       # On push to "master", build or change infrastructure according to Terraform configuration files
-#       # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
-#     # - name: Terraform Apply
-#     #   if: github.ref == 'refs/heads/"master"' && github.event_name == 'push'
-#     #   run: terraform apply -auto-approve -input=false
-#    #***************
-#    # dboedited
-#    #*************
-#     - name: Terraform apply
-#       uses: hashicorp/terraform-github-actions@master
-#       with:
-#         tf_actions_version: 0.14.3
-#         tf_actions_subcommand: 'apply'
-#         tf_actions_working_dir: '.'
-#         tf_actions_comment: true
-#         args: '-auto-approve -var="instance_type=t2.medium"'
+    # Generates an execution plan for Terraform
+   #***************
+   # dboedited
+   #*************
+    - name: Terraform Plan
+      uses: hashicorp/terraform-github-actions@master
+      with:
+        tf_actions_version: 0.14.3
+        tf_actions_subcommand: 'plan'
+        tf_actions_working_dir: '.'
+        tf_actions_comment: true
+        args: '-var="instance_type=t2.medium"'
 
-#       - name: Terraform destroy
-#       if: ${{ github.event.inputs.terraform_action == 'destroy' }}
-#       uses: hashicorp/terraform-github-actions@master
-#       with:
-#         tf_actions_version: 0.14.3
-#         tf_actions_subcommand: ${{ github.event.inputs.terraform_action }}
-#         tf_actions_working_dir: '.'
-#         tf_actions_comment: true
-#         args: '-auto-approve -var="instance_type=t2.medium"'
+      # On push to "master", build or change infrastructure according to Terraform configuration files
+      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
+    # - name: Terraform Apply
+    #   if: github.ref == 'refs/heads/"master"' && github.event_name == 'push'
+    #   run: terraform apply -auto-approve -input=false
+   #***************
+   # dboedited
+   #*************
+    - name: Terraform apply
+      uses: hashicorp/terraform-github-actions@master
+      with:
+        tf_actions_version: 0.14.3
+        tf_actions_subcommand: 'apply'
+        tf_actions_working_dir: '.'
+        tf_actions_comment: true
+        args: '-auto-approve -var="instance_type=t2.medium"'
+
+      - name: Terraform destroy
+      if: ${{ github.event.inputs.terraform_action == 'destroy' }}
+      uses: hashicorp/terraform-github-actions@master
+      with:
+        tf_actions_version: 0.14.3
+        tf_actions_subcommand: ${{ github.event.inputs.terraform_action }}
+        tf_actions_working_dir: '.'
+        tf_actions_comment: true
+        args: '-auto-approve -var="instance_type=t2.medium"'
 
 # *********************************************************
 
@@ -285,20 +289,20 @@ jobs:
       #     zip -r app.zip ./*
       #     cp app.zip lex-terraform-anlam-10-4-23/app.zip
       #     cd ../..
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-      - name: Terraform Init
-        id: init
-        run: |
-          terraform init
-      - name: Terraform Plan
-        id: plan
-        run: |
-          terraform plan -no-color -input=false
-        continue-on-error: true
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-      - name: Terraform Apply
-        run: |
-          terraform apply -auto-approve -input=false
+      # - name: Setup Terraform
+      #   uses: hashicorp/setup-terraform@v1
+      # - name: Terraform Init
+      #   id: init
+      #   run: |
+      #     terraform init
+      # - name: Terraform Plan
+      #   id: plan
+      #   run: |
+      #     terraform plan -no-color -input=false
+      #   continue-on-error: true
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+      # - name: Terraform Apply
+      #   run: |
+      #     terraform apply -auto-approve -input=false
